/** Public download entry for a local copy — same URLs as the GitHub README intro. */

export const GITHUB_REPO_URL = 'https://github.com/CarryLewis/ECG-stimulator'

export const GITHUB_API_COMMITS_MAIN =
  'https://api.github.com/repos/CarryLewis/ECG-stimulator/commits/main'

/** Live snapshot of current `main` — generated by GitHub at download time. */
export const SOURCE_ZIP_URL = `${GITHUB_REPO_URL}/archive/refs/heads/main.zip`

/** Rolling view bundle. Recreated on every `main` push (tag `local-latest`). */
export const VIEW_ZIP_URL = `${GITHUB_REPO_URL}/releases/download/local-latest/ecg-stimulator-view.zip`

/** Chinese README heading that GitHub slugifies as the download entry. */
export const README_DOWNLOAD_ZH_URL = `${GITHUB_REPO_URL}#本地下载与调试`

export const README_DOWNLOAD_EN_URL = `${GITHUB_REPO_URL}#download-locally-and-debug`

export const CLONE_COMMAND =
  'git clone https://github.com/CarryLewis/ECG-stimulator.git'

export interface LatestMainCommit {
  sha: string
  shortSha: string
  date: string
  sourceZipUrl: string
}

export function sourceZipUrlForSha(sha: string): string {
  return `${GITHUB_REPO_URL}/archive/${sha}.zip`
}

export function viewZipUrlNow(nowMs: number = Date.now()): string {
  return `${VIEW_ZIP_URL}?t=${nowMs}`
}

interface GithubCommitPayload {
  sha?: unknown
  commit?: { committer?: { date?: unknown } }
}

export async function resolveLatestMainCommit(
  fetchImpl: typeof fetch = fetch,
): Promise<LatestMainCommit | null> {
  try {
    const response = await fetchImpl(GITHUB_API_COMMITS_MAIN, {
      headers: { Accept: 'application/vnd.github+json' },
    })
    if (!response.ok) return null
    const payload = (await response.json()) as GithubCommitPayload
    if (typeof payload.sha !== 'string' || payload.sha.length < 7) return null
    const date =
      typeof payload.commit?.committer?.date === 'string'
        ? payload.commit.committer.date
        : ''
    return {
      sha: payload.sha,
      shortSha: payload.sha.slice(0, 7),
      date,
      sourceZipUrl: sourceZipUrlForSha(payload.sha),
    }
  } catch {
    return null
  }
}
